dist: bionic

language: python

python:
  - '3.7'

services:
  - docker

before_install:
  - docker-compose -f Activity-7/docker-compose.yml up --build -d
  - pip install -r requirements.txt

script:
  - pytest test_project.py
  - flake8 . --count --show-source --statistics

after_script:
  - docker-compose down
