dist: bionic

language: python

python:
  - '3.7'

services:
  - docker

before_install:
  - docker-compose -f Activity-2/Test/web/docker-compose.yml up --build -d
  - pip install -r Activity-2/Test/requirements.txt

script:
  - pytest Activity-2/Test/test.py
  - flake8 . --count --show-source --statistics

after_script:
  - docker-compose down
