DROP DATABASE IF EXISTS db;
CREATE DATABASE db;
USE db;

DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS video;
CREATE TABLE users(
	UID INTEGER NOT NULL AUTO_INCREMENT,
	Username VARCHAR(30) NOT NULL,
	HashedPass VARCHAR(128) NOT NULL,
	VideoCount INTEGER,
	CreationDate DATE,
	Email VARCHAR(50),
	CONSTRAINT users_pk PRIMARY KEY(UID)
);

CREATE TABLE video(
	VID INTEGER NOT NULL AUTO_INCREMENT,
	UID INTEGER NOT NULL,
	VideoOwner VARCHAR(30) NOT NULL,
	VideoTitle VARCHAR(100),
	VideoURL VARCHAR(2000),
	DateUploaded DATE,
	CONSTRAINT Video_pk PRIMARY KEY(VID),
	CONSTRAINT Video_fk FOREIGN KEY (UID)
		REFERENCES users(UID)
			ON DELETE CASCADE
			ON UPDATE CASCADE
);